version: "3.9"

services:
    server:
        container_name: server
        image: thediep094/server:latest
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - PORT=8000
            - URL=mongodb+srv://thediep094:diep0904@lolremake.rubj7zs.mongodb.net/test
            - SECRET_KEY_ACCESS=secret123456
            - SECRET_KEY_REFRESH=secret78910
            - ACCESS_TOKEN_EXPIRE=60
            - REFRESH_TOKEN_EXPIRE=20160
            - RIOT_KEY=RGAPI-0bb668e8-f08a-41ba-b625-3fca0604eb87
        ports:
            - "8080:8000"
