const express = require("express");
const authRouter = require("./auth.route");
const userRouter = require("./user.route");
const BoxChatRouter = require("./boxChat.route");
const messageRouter = require("./message.route");
const productRouter = require("./product.route");
const ingameRouter = require("./ingame.route");
const rankRouter = require("./rank.route");
const newRouter = require("./new.route");
const cartRouter = require("./cart.route");
const commentRouter = require("./comment.route");
const commentNewsRouter = require("./commentNews.route");
const orderRouter = require("./order.route");
const friendRouter = require("./friend.route");
const walletRouter = require("./wallet.route");
const purchaseItem = require("./purchaseItem.route");
const router = express.Router();

router.use("/rank", rankRouter);
router.use("/ingame", ingameRouter);
router.use("/products", productRouter);
router.use("/users", userRouter);
router.use("/auth", authRouter);
router.use("/chat", BoxChatRouter);
router.use("/message", messageRouter);
router.use("/comment", commentRouter);
router.use("/comment-news", commentNewsRouter);
router.use("/friend", friendRouter);
router.use("/new", newRouter);
router.use("/cart", cartRouter);
router.use("/order", orderRouter);
router.use("/wallet", walletRouter);
router.use("/purchase-item", purchaseItem);

module.exports = router;
